import { cleanText } from "./text.js";

export function formatApplicationPacketResult(result) {
  const packet = result.packet ?? {};
  const generation = result.generation ?? null;
  const title = buildDeliverableTitle(packet);
  const summary = buildDeliverableSummary(packet, generation);
  const markdown = buildDeliverableMarkdown(packet, generation, title, summary);

  return {
    ok: true,
    service: result.service || "Vouch",
    version: result.version,
    type: "vouch.application_packet",
    title,
    summary,
    deliverable: {
      title,
      summary,
      format: "markdown+json",
      markdown,
      packet,
      generation
    },
    content: [
      {
        type: "text",
        text: markdown
      },
      {
        type: "json",
        json: {
          packet,
          generation
        }
      }
    ],
    structuredContent: {
      service: result.service || "Vouch",
      version: result.version,
      packet,
      generation
    },
    packet,
    generation
  };
}

function buildDeliverableTitle(packet) {
  const firstJob = packet.jobBreakdown?.[0];
  const company = cleanText(firstJob?.company);
  const role = cleanText(firstJob?.title) || "target role";

  return company
    ? `Vouch Resume-to-Offer Packet for ${company} ${role}`
    : `Vouch Resume-to-Offer Packet for ${role}`;
}

function buildDeliverableSummary(packet, generation) {
  const before = numberOrDash(packet.fitScoreBefore);
  const after = numberOrDash(packet.fitScoreAfter);
  const decision = cleanText(packet.mockRecruiterScreen?.decision) || "Recruiter screen included";
  const model = cleanText(generation?.model);
  const provider = cleanText(generation?.provider);
  const source = provider ? ` Generated by ${provider}${model ? ` (${model})` : ""}.` : "";

  return `Fit score improved from ${before} to ${after}. ${decision}.${source}`;
}

function buildDeliverableMarkdown(packet, generation, title, summary) {
  return [
    `# ${title}`,
    "",
    summary,
    "",
    "## Fit Benchmark",
    `- Before score: ${numberOrDash(packet.fitScoreBefore)}`,
    `- After score: ${numberOrDash(packet.fitScoreAfter)}`,
    "",
    "## Recruiter Summary",
    cleanText(packet.recruiterSummary) || "No recruiter summary returned.",
    "",
    "## ATS Resume",
    cleanText(packet.atsResume) || "No ATS resume returned.",
    "",
    "## Mock Recruiter Screen",
    formatRecruiterScreen(packet.mockRecruiterScreen),
    "",
    "## Interview Prep",
    formatInterviewPrep(packet.interviewPrep),
    "",
    "## Portfolio Proof Sprints",
    formatPortfolioProjects(packet.portfolioProjects),
    "",
    "## Salary Positioning",
    formatObjectLines(packet.salaryPositioning),
    "",
    "## Fit Gaps",
    formatGapBenchmark(packet.gapBenchmark),
    "",
    "## Generation",
    formatObjectLines(generation)
  ].join("\n");
}

function formatRecruiterScreen(screen) {
  if (!screen || typeof screen !== "object") {
    return "No mock recruiter screen returned.";
  }

  return [
    `Decision: ${cleanText(screen.decision) || "Not specified"}`,
    formatList("Why interview", screen.whyInterview),
    formatList("Concerns", screen.concerns),
    formatQuestions(screen.screeningQuestions)
  ].filter(Boolean).join("\n");
}

function formatInterviewPrep(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "No interview prep returned.";
  }

  return items.map((item, index) => [
    `${index + 1}. ${cleanText(item.question) || "Interview question"}`,
    `   Why asked: ${cleanText(item.whyAsked) || "Role relevance"}`,
    `   Answer frame: ${cleanText(item.answerFrame) || "Use a specific, evidence-backed story."}`
  ].join("\n")).join("\n");
}

function formatPortfolioProjects(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "No portfolio projects returned.";
  }

  return items.map((item, index) => [
    `${index + 1}. ${cleanText(item.title) || "Proof sprint"}`,
    `   Objective: ${cleanText(item.objective) || "Show role evidence."}`,
    `   Deliverable: ${cleanText(item.deliverable) || "Concise proof artifact."}`,
    `   Timeline: ${cleanText(item.timeline) || "Not specified"}`
  ].join("\n")).join("\n");
}

function formatGapBenchmark(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "No gaps returned.";
  }

  return items.map((item) => {
    const status = cleanText(item.status) || "unknown";
    const requirement = cleanText(item.requirement) || "requirement";
    const recommendation = cleanText(item.recommendation);
    return `- ${requirement}: ${status}${recommendation ? ` - ${recommendation}` : ""}`;
  }).join("\n");
}

function formatQuestions(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "";
  }

  return [
    "Screening questions:",
    ...items.map((item) => `- ${cleanText(item.question) || cleanText(item.topic) || "Question"}`)
  ].join("\n");
}

function formatObjectLines(value) {
  if (!value || typeof value !== "object") {
    return "Not returned.";
  }

  return Object.entries(value)
    .map(([key, entryValue]) => `- ${splitCamelCase(key)}: ${formatValue(entryValue)}`)
    .join("\n");
}

function formatList(label, values) {
  if (!Array.isArray(values) || values.length === 0) {
    return "";
  }

  return `${label}:\n${values.map((value) => `- ${cleanText(value)}`).join("\n")}`;
}

function formatValue(value) {
  if (Array.isArray(value)) {
    return value.map((item) => cleanText(item)).filter(Boolean).join("; ");
  }

  if (value && typeof value === "object") {
    return JSON.stringify(value);
  }

  return cleanText(value) || "Not specified";
}

function splitCamelCase(value) {
  return cleanText(value)
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .toLowerCase();
}

function numberOrDash(value) {
  return Number.isFinite(value) ? value : "-";
}
